// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI tool to suggest stylistic adaptations based on trending design elements.
 *
 * - suggestStyleAdaptations - A function that suggests stylistic adaptations.
 * - SuggestStyleAdaptationsInput - The input type for the suggestStyleAdaptations function.
 * - SuggestStyleAdaptationsOutput - The return type for the suggestStyleAdaptations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestStyleAdaptationsInputSchema = z.object({
  currentStyleDescription: z
    .string()
    .describe('A description of the current website style.'),
});
export type SuggestStyleAdaptationsInput = z.infer<
  typeof SuggestStyleAdaptationsInputSchema
>;

const SuggestStyleAdaptationsOutputSchema = z.object({
  suggestedAdaptations: z
    .string()
    .describe(
      'A list of suggested stylistic adaptations based on trending design elements.'
    ),
});
export type SuggestStyleAdaptationsOutput = z.infer<
  typeof SuggestStyleAdaptationsOutputSchema
>;

export async function suggestStyleAdaptations(
  input: SuggestStyleAdaptationsInput
): Promise<SuggestStyleAdaptationsOutput> {
  return suggestStyleAdaptationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestStyleAdaptationsPrompt',
  input: {schema: SuggestStyleAdaptationsInputSchema},
  output: {schema: SuggestStyleAdaptationsOutputSchema},
  prompt: `You are a web design expert. Given the current style description, suggest stylistic adaptations based on trending design elements.

Current Style Description: {{{currentStyleDescription}}}

Suggested Adaptations:`,
});

const suggestStyleAdaptationsFlow = ai.defineFlow(
  {
    name: 'suggestStyleAdaptationsFlow',
    inputSchema: SuggestStyleAdaptationsInputSchema,
    outputSchema: SuggestStyleAdaptationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
