
export interface Product {
    id: string;
    brand: string;
    name: string;
    image: string;
    rating: number;
    reviews: number;
    questions: number;
    price: string;
    href: string;
    hint?: string;
    quantity?: number;
    description?: string;
    features?: string[];
    specs?: { [key: string]: string };
    collection?: string;
}

export const products: Product[] = [
  {
    id: 'aiko-a465',
    brand: 'AIKO',
    name: 'AIKO-A465-MAH54Db-Neostar-2S+ M-188 465 Wp schwarz',
    price: '99.00',
    image: 'https://picsum.photos/seed/aiko-a465/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/aiko-a465',
    hint: 'solar panel',
    collection: '0 % Bestandsartikel',
  },
  {
    id: 'anker-548-powerbank',
    brand: 'ANKER',
    name: 'ANKER 548 Powerbank 192 Wh',
    price: '189.00',
    image: 'https://picsum.photos/seed/anker-548/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/anker-548-powerbank',
    hint: 'power bank',
    collection: 'Powerbanks',
  },
  {
    id: 'anker-737-powerbank',
    brand: 'ANKER',
    name: 'ANKER 737 PowerBank 140 W B-Ware',
    price: '113.00',
    image: 'https://picsum.photos/seed/anker-737/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/anker-737-powerbank',
    hint: 'power bank',
    collection: 'Everything for Home',
  },
  {
    id: 'anker-prime-powerbank',
    brand: 'ANKER',
    name: 'ANKER Prime Powerbank 20 000 mAh (200 W)',
    price: '109.00',
    image: 'https://picsum.photos/seed/anker-prime/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/anker-prime-powerbank',
    hint: 'power bank',
    collection: 'Powerbanks',
  },
  {
    id: 'ecoflow-delta-2-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow Delta 2 B-Ware',
    price: '541.00',
    image: 'https://picsum.photos/seed/ecoflow-delta-2/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-delta-2-bware',
    hint: 'power station',
    collection: 'EcoFlow Outlet',
  },
  {
    id: 'ecoflow-river-2-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow River 2 B-Ware',
    price: '235.00',
    image: 'https://picsum.photos/seed/ecoflow-river-2/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-river-2-bware',
    hint: 'power station',
    collection: 'EcoFlow Outlet',
  },
  {
    id: 'ecoflow-delta-pro-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow Delta Pro Powerstation B-Ware',
    price: '1329.00',
    image: 'https://picsum.photos/seed/ecoflow-delta-pro/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-delta-pro-bware',
    hint: 'power station',
    collection: 'Everything for Home',
  },
  {
    id: 'ecoflow-river-2-pro-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow River 2 Pro B-Ware',
    price: '427.00',
    image: 'https://picsum.photos/seed/ecoflow-river-2-pro/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-river-2-pro-bware',
    hint: 'power station',
    collection: 'Outlet',
  },
  {
    id: 'ugreen-solarpanel-bware',
    brand: 'UGREEN',
    name: 'UGREEN Faltbares Solarpanel 100 W B-Ware',
    price: '129.00',
    image: 'https://picsum.photos/seed/ugreen-solar/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ugreen-solarpanel-bware',
    hint: 'solar panel',
    collection: 'Outlet',
  },
  {
    id: 'roborock-s8-pro-ultra-bware',
    brand: 'Roborock',
    name: 'Roborock S8 Pro Ultra B-Ware',
    price: '1349.00',
    image: 'https://picsum.photos/seed/roborock-s8/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/roborock-s8-pro-ultra-bware',
    hint: 'robot vacuum',
    collection: 'Roborock',
  },
  {
    id: 'zendure-solarflow-hub-bware',
    brand: 'Zendure',
    name: 'Zendure SolarFlow Smart PV Hub 1200 W 2x MPPT Regler B-Ware',
    price: '151.00',
    image: 'https://picsum.photos/seed/zendure-hub/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/zendure-solarflow-hub-bware',
    hint: 'solar hub',
    collection: 'Zendure Outlet',
  },
  {
    id: 'zendure-solarflow-ab2000-bware',
    brand: 'Zendure',
    name: 'Zendure SolarFlow AB2000 Zusatzbatterie 1920 Wh B-Ware',
    price: '531.00',
    image: 'https://picsum.photos/seed/zendure-battery/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/zendure-solarflow-ab2000-bware',
    hint: 'solar battery',
    collection: 'Zendure Outlet',
  },
  {
    id: 'dometic-cfx3-25-bware',
    brand: 'Dometic',
    name: 'Dometic CFX3 25 mobile Kompressorkühlbox B-Ware',
    price: '712.00',
    image: 'https://picsum.photos/seed/dometic-cfx3-25/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/dometic-cfx3-25-bware',
    hint: 'cooler box',
    collection: 'Dometic Outlet',
  },
  {
    id: 'dometic-cfx3-35-bware',
    brand: 'Dometic',
    name: 'Dometic CFX3 35 mobile Kompressorkühlbox B-Ware',
    price: '759.00',
    image: 'https://picsum.photos/seed/dometic-cfx3-35/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/dometic-cfx3-35-bware',
    hint: 'cooler box',
    collection: 'Dometic Outlet',
  },
  {
    id: 'trina-vertex-s-435w',
    brand: 'Trina Solar',
    name: 'Trina Vertex S+ 435 W N-Type Bifaziales Dual Glass PV-Modul',
    price: '65.00 - 2784.60',
    image: 'https://picsum.photos/seed/trina-vertex-435/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/trina-vertex-s-435w',
    hint: 'solar panel',
    collection: 'Trina Solar',
  },
  {
    id: 'trina-vertex-s-440w',
    brand: 'Trina Solar',
    name: 'Trina Vertex S+ 440 W',
    price: '65.00 - 2784.60',
    image: 'https://picsum.photos/seed/trina-vertex-440/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/trina-vertex-s-440w',
    hint: 'solar panel',
    collection: 'Trina Solar',
  },
  {
    id: 'ecoflow-delta-3-plus',
    brand: 'EcoFlow',
    name: 'EcoFlow Delta 3 Plus Powerstation',
    price: '660.00',
    image: 'https://picsum.photos/seed/ecoflow-delta-3/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-delta-3-plus',
    hint: 'power station',
    collection: 'EcoFlow Outlet',
  },
  {
    id: 'sanus-era-300-wall-mount',
    brand: 'SANUS',
    name: 'SANUS ERA 300 wall mount',
    price: '44.99',
    image: 'https://picsum.photos/seed/sanus-era300-wall/400/400',
    rating: 5.0,
    reviews: 1,
    questions: 0,
    href: '/products/sanus-era-300-wall-mount',
    hint: 'wall mount',
    collection: 'Everything for Home',
  },
  {
    id: 'flexson-era-300-wall-mount',
    brand: 'Flexson',
    name: 'Flexson ERA 300 wall mount',
    price: '39.99',
    image: 'https://picsum.photos/seed/flexson-era300-wall/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/flexson-era-300-wall-mount',
    hint: 'wall mount',
    collection: 'Everything for Home',
  },
  {
    id: 'flexson-era-100-wall-mount',
    brand: 'Flexson',
    name: 'Flexson ERA 100 wall mount',
    price: '34.99',
    image: 'https://picsum.photos/seed/flexson-era100-wall/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/flexson-era-100-wall-mount',
    hint: 'wall mount',
    collection: 'Everything for Home',
  },
  {
    id: 'sanus-era-100-wall-mount',
    brand: 'SANUS',
    name: 'SANUS ERA 100 wall mount',
    price: '44.99',
    image: 'https://picsum.photos/seed/sanus-era100-wall/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/sanus-era-100-wall-mount',
    hint: 'wall mount',
    collection: 'Everything for Home',
  },
  {
    id: 'flexson-era-100-stand',
    brand: 'Flexson',
    name: 'Flexson ERA 100 Stand',
    price: '79.99',
    image: 'https://picsum.photos/seed/flexson-era100-stand/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/flexson-era-100-stand',
    hint: 'speaker stand',
    collection: 'Everything for Home',
  },
  {
    id: 'sanus-era-100-stand',
    brand: 'SANUS',
    name: 'SANUS ERA 100 Stand',
    price: '84.99',
    image: 'https://picsum.photos/seed/sanus-era100-stand/400/400',
    rating: 5.0,
    reviews: 1,
    questions: 0,
    href: '/products/sanus-era-100-stand',
    hint: 'speaker stand',
    collection: 'Everything for Home',
  },
  {
    id: 'sanus-era-300-stand',
    brand: 'SANUS',
    name: 'SANUS ERA 300 Stand',
    price: '114.99',
    image: 'https://picsum.photos/seed/sanus-era300-stand/400/400',
    rating: 5.0,
    reviews: 2,
    questions: 1,
    href: '/products/sanus-era-300-stand',
    hint: 'speaker stand',
    collection: 'Everything for Home',
  },
  {
    id: 'sanus-era-300-height-adjustable-stand',
    brand: 'SANUS',
    name: 'SANUS ERA 300 height-adjustable stand',
    price: '169.99',
    image: 'https://picsum.photos/seed/sanus-era300-adj-stand/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/sanus-era-300-height-adjustable-stand',
    hint: 'speaker stand',
    collection: 'Everything for Home',
  },
  {
    id: 'sanus-era-100-height-adjustable-stand',
    brand: 'SANUS',
    name: 'SANUS ERA 100 height-adjustable stand',
    price: '124.99',
    image: 'https://picsum.photos/seed/sanus-era100-adj-stand/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/sanus-era-100-height-adjustable-stand',
    hint: 'speaker stand',
    collection: 'Everything for Home',
  },
  {
    id: 'flexson-era-300-standfuss',
    brand: 'Flexson',
    name: 'Flexson ERA 300 Standfuß',
    price: '99.99',
    image: 'https://picsum.photos/seed/flexson-era300-stand/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/flexson-era-300-standfuss',
    hint: 'speaker stand',
    collection: 'Everything for Home',
  },
  {
    id: 'dtron-cms65-outdoor-speaker',
    brand: 'dtron',
    name: 'dtron CMS65 Outdoor Lautsprecher IPX 6 (Pair)',
    price: '149.00',
    image: 'https://picsum.photos/seed/dtron-speaker/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/dtron-cms65-outdoor-speaker',
    hint: 'outdoor speaker',
    collection: 'Everything for Home',
  },
  {
    id: 'purelink-pls15w-50-cable',
    brand: 'PureLink',
    name: 'PureLink PLS15W-50 Lautsprecherkabel 2x 1,5mm², 50m',
    price: '49.00',
    image: 'https://picsum.photos/seed/purelink-cable/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/purelink-pls15w-50-cable',
    hint: 'speaker cable',
    collection: 'Everything for Home',
  },
  {
    id: 'ecoflow-river-2-max',
    brand: 'EcoFlow',
    name: 'EcoFlow River 2 Max',
    price: '599.00',
    image: 'https://picsum.photos/seed/ecoflow-river-2-max/400/400',
    rating: 4.8,
    reviews: 120,
    questions: 15,
    href: '/products/ecoflow-river-2-max',
    hint: 'power station',
    collection: 'Everything for Home',
  }
];
