
export interface Product {
    id: string;
    brand: string;
    name: string;
    image: string;
    rating: number;
    reviews: number;
    questions: number;
    price: string;
    href: string;
    hint?: string;
    quantity?: number;
    description?: string;
    features?: string[];
    specs?: { [key: string]: string };
}

export const products: Product[] = [
    {
        id: 'flexson-era-100-ceiling-holder',
        brand: 'Flexson',
        name: 'Flexson ERA 100 Ceiling Holder',
        image: 'https://picsum.photos/seed/flexson-era-100-ceiling-holder/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '79,99',
        href: '/products/flexson-era-100-ceiling-holder',
        hint: 'ceiling holder',
    },
    {
        id: 'flexson-era-100-stand',
        brand: 'Flexson',
        name: 'Flexson ERA 100 Stand',
        image: 'https://picsum.photos/seed/flexson-era-100-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '69,99 - 119,00',
        href: '/products/flexson-era-100-stand',
        hint: 'speaker stand',
    },
    {
        id: 'flexson-era-100-table-stand',
        brand: 'Flexson',
        name: 'Flexson ERA 100 Table Stand',
        image: 'https://picsum.photos/seed/flexson-era-100-table-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '25,99',
        href: '/products/flexson-era-100-table-stand',
        hint: 'table stand',
    },
    {
        id: 'flexson-era-100-wall-mount',
        brand: 'Flexson',
        name: 'Flexson ERA 100 wall mount',
        image: 'https://picsum.photos/seed/flexson-era-100-wall-mount/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '32,90 - 49,00',
        href: '/products/flexson-era-100-wall-mount',
        hint: 'wall mount',
    },
    {
        id: 'flexson-era-300-ceiling-holder',
        brand: 'Flexson',
        name: 'Flexson ERA 300 Ceiling Holder',
        image: 'https://picsum.photos/seed/flexson-era-300-ceiling-holder/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '119,99',
        href: '/products/flexson-era-300-ceiling-holder',
        hint: 'ceiling holder',
    },
    {
        id: 'flexson-era-300-stand',
        brand: 'Flexson',
        name: 'Flexson ERA 300 Stand',
        image: 'https://picsum.photos/seed/flexson-era-300-stand/400/400',
        rating: 5,
        reviews: 1,
        questions: 0,
        price: '119,99',
        href: '/products/flexson-era-300-stand',
        hint: 'speaker stand',
    },
    {
        id: 'flexson-era-300-table-stand',
        brand: 'Flexson',
        name: 'Flexson ERA 300 Table Stand',
        image: 'https://picsum.photos/seed/flexson-era-300-table-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '34,99',
        href: '/products/flexson-era-300-table-stand',
        hint: 'table stand',
    },
    {
        id: 'flexson-era-300-wall-mount',
        brand: 'Flexson',
        name: 'Flexson ERA 300 wall mount',
        image: 'https://picsum.photos/seed/flexson-era-300-wall-mount/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '64,99',
        href: '/products/flexson-era-300-wall-mount',
        hint: 'wall mount',
    },
    {
        id: 'flexson-era100-security-kit',
        brand: 'Flexson',
        name: 'Flexson ERA100 security kit wall holder',
        image: 'https://picsum.photos/seed/flexson-era100-security-kit/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '19,99',
        href: '/products/flexson-era100-security-kit',
        hint: 'security kit',
    },
    {
        id: 'flexson-era100-one-ceiling-mount',
        brand: 'Flexson',
        name: 'Flexson ERA100/ONE FLXE100ICM1011 Built-in ceiling/wall mount',
        image: 'https://picsum.photos/seed/flexson-era100-one-ceiling-mount/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '119,99',
        href: '/products/flexson-era100-one-ceiling-mount',
        hint: 'ceiling mount',
    },
    {
        id: 'flexson-five-stand',
        brand: 'Flexson',
        name: 'Flexson Five stand vertical/horizontal',
        image: 'https://picsum.photos/seed/flexson-five-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '129,99',
        href: '/products/flexson-five-stand',
        hint: 'speaker stand',
    },
    {
        id: 'flexson-move-2-stand',
        brand: 'Flexson',
        name: 'Flexson Move 2 Stand FLXSMFS1051 Black',
        image: 'https://picsum.photos/seed/flexson-move-2-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '149,99',
        href: '/products/flexson-move-2-stand',
        hint: 'speaker stand',
    },
    {
        id: 'flexson-one-play1-stand',
        brand: 'Flexson',
        name: 'Flexson One/One SL/Play 1 stand',
        image: 'https://picsum.photos/seed/flexson-one-play1-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '39,00 - 79,00',
        href: '/products/flexson-one-play1-stand',
        hint: 'speaker stand',
    },
    {
        id: 'flexson-one-play1-ceiling-holder',
        brand: 'Flexson',
        name: 'Flexson One/One SL/Play:1 ceiling holder',
        image: 'https://picsum.photos/seed/flexson-one-play1-ceiling-holder/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '69,00 - 139,99',
        href: '/products/flexson-one-play1-ceiling-holder',
        hint: 'ceiling holder',
    },
    {
        id: 'flexson-one-play1-wall-holder',
        brand: 'Flexson',
        name: 'Flexson One/One SL/Play:1 wall holder',
        image: 'https://picsum.photos/seed/flexson-one-play1-wall-holder/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '64,99',
        href: '/products/flexson-one-play1-wall-holder',
        hint: 'wall holder',
    },
    {
        id: 'sanus-five-stand',
        brand: 'SANUS',
        name: 'SANUS Five stand',
        image: 'https://picsum.photos/seed/sanus-five-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '139,99',
        href: '/products/sanus-five-stand',
        hint: 'speaker stand',
    },
    {
        id: 'flexson-one-play1-wall-mount',
        brand: 'Flexson',
        name: 'Flexson One/One SL/Play:1 wall mount',
        image: 'https://picsum.photos/seed/flexson-one-play1-wall-mount/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '19,00',
        href: '/products/flexson-one-play1-wall-mount',
        hint: 'wall mount',
    },
    {
        id: 'sanus-era-100-height-adjustable-stand',
        brand: 'SANUS',
        name: 'SANUS ERA 100 height-adjustable stand',
        image: 'https://picsum.photos/seed/sanus-era-100-height-adjustable-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '124,99 - 214,99',
        href: '/products/sanus-era-100-height-adjustable-stand',
        hint: 'speaker stand',
    },
    {
        id: 'sanus-era-100-stand',
        brand: 'SANUS',
        name: 'SANUS ERA 100 Stand',
        image: 'https://picsum.photos/seed/sanus-era-100-stand/400/400',
        rating: 5,
        reviews: 1,
        questions: 0,
        price: '84,99 - 129,99',
        href: '/products/sanus-era-100-stand',
        hint: 'speaker stand',
    },
    {
        id: 'sanus-era-100-wall-mount',
        brand: 'SANUS',
        name: 'SANUS ERA 100 wall mount',
        image: 'https://picsum.photos/seed/sanus-era-100-wall-mount/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '44,99 - 69,99',
        href: '/products/sanus-era-100-wall-mount',
        hint: 'wall mount',
    },
    {
        id: 'sanus-era-300-height-adjustable-stand',
        brand: 'SANUS',
        name: 'SANUS ERA 300 height-adjustable stand',
        image: 'https://picsum.photos/seed/sanus-era-300-height-adjustable-stand/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '169,99 - 279,99',
        href: '/products/sanus-era-300-height-adjustable-stand',
        hint: 'speaker stand',
    },
    {
        id: 'sanus-era-300-stand',
        brand: 'SANUS',
        name: 'SANUS ERA 300 Stand',
        image: 'https://picsum.photos/seed/sanus-era-300-stand/400/400',
        rating: 5,
        reviews: 2,
        questions: 1,
        price: '114,99 - 199,99',
        href: '/products/sanus-era-300-stand',
        hint: 'speaker stand',
    },
    {
        id: 'sanus-era-300-wall-mount',
        brand: 'SANUS',
        name: 'SANUS ERA 300 wall mount',
        image: 'https://picsum.photos/seed/sanus-era-300-wall-mount/400/400',
        rating: 5,
        reviews: 1,
        questions: 0,
        price: '54,99 - 89,99',
        href: '/products/sanus-era-300-wall-mount',
        hint: 'wall mount',
    },
    {
        id: 'sanus-five-stands',
        brand: 'SANUS',
        name: 'SANUS Five stand',
        image: 'https://picsum.photos/seed/sanus-five-stands/400/400',
        rating: 0,
        reviews: 0,
        questions: 0,
        price: '139,99',
        href: '/products/sanus-five-stands',
        hint: 'speaker stand',
    }
];

    