
export interface Product {
    id: string;
    brand: string;
    name: string;
    image: string;
    rating: number;
    reviews: number;
    questions: number;
    price: string;
    href: string;
    hint?: string;
    quantity?: number;
    description?: string;
    features?: string[];
    specs?: { [key: string]: string };
    collection?: string;
}

export const products: Product[] = [
  {
    id: 'aiko-a465',
    brand: 'AIKO',
    name: 'AIKO-A465-MAH54Db-Neostar-2S+ M-188 465 Wp schwarz',
    price: '99.00',
    image: 'https://picsum.photos/seed/aiko-a465/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/aiko-a465',
    hint: 'solar panel',
    collection: '0 % Bestandsartikel',
  },
  {
    id: 'anker-548-powerbank',
    brand: 'ANKER',
    name: 'ANKER 548 Powerbank 192 Wh',
    price: '189.00',
    image: 'https://picsum.photos/seed/anker-548/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/anker-548-powerbank',
    hint: 'power bank',
    collection: 'Powerbanks',
  },
  {
    id: 'anker-737-powerbank',
    brand: 'ANKER',
    name: 'ANKER 737 PowerBank 140 W B-Ware',
    price: '113.00',
    image: 'https://picsum.photos/seed/anker-737/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/anker-737-powerbank',
    hint: 'power bank',
    collection: 'Powerbanks',
  },
  {
    id: 'anker-prime-powerbank',
    brand: 'ANKER',
    name: 'ANKER Prime Powerbank 20 000 mAh (200 W)',
    price: '109.00',
    image: 'https://picsum.photos/seed/anker-prime/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/anker-prime-powerbank',
    hint: 'power bank',
    collection: 'Powerbanks',
  },
  {
    id: 'ecoflow-delta-2-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow Delta 2 B-Ware',
    price: '541.00',
    image: 'https://picsum.photos/seed/ecoflow-delta-2/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-delta-2-bware',
    hint: 'power station',
    collection: 'EcoFlow Outlet',
  },
  {
    id: 'ecoflow-river-2-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow River 2 B-Ware',
    price: '235.00',
    image: 'https://picsum.photos/seed/ecoflow-river-2/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-river-2-bware',
    hint: 'power station',
    collection: 'EcoFlow Outlet',
  },
  {
    id: 'ecoflow-delta-pro-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow Delta Pro Powerstation B-Ware',
    price: '1329.00',
    image: 'https://picsum.photos/seed/ecoflow-delta-pro/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-delta-pro-bware',
    hint: 'power station',
    collection: 'EcoFlow Outlet',
  },
  {
    id: 'ecoflow-river-2-pro-bware',
    brand: 'EcoFlow',
    name: 'EcoFlow River 2 Pro B-Ware',
    price: '427.00',
    image: 'https://picsum.photos/seed/ecoflow-river-2-pro/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-river-2-pro-bware',
    hint: 'power station',
    collection: 'Outlet',
  },
  {
    id: 'ugreen-solarpanel-bware',
    brand: 'UGREEN',
    name: 'UGREEN Faltbares Solarpanel 100 W B-Ware',
    price: '129.00',
    image: 'https://picsum.photos/seed/ugreen-solar/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ugreen-solarpanel-bware',
    hint: 'solar panel',
    collection: 'Outlet',
  },
  {
    id: 'roborock-s8-pro-ultra-bware',
    brand: 'Roborock',
    name: 'Roborock S8 Pro Ultra B-Ware',
    price: '1349.00',
    image: 'https://picsum.photos/seed/roborock-s8/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/roborock-s8-pro-ultra-bware',
    hint: 'robot vacuum',
    collection: 'Roborock',
  },
  {
    id: 'zendure-solarflow-hub-bware',
    brand: 'Zendure',
    name: 'Zendure SolarFlow Smart PV Hub 1200 W 2x MPPT Regler B-Ware',
    price: '151.00',
    image: 'https://picsum.photos/seed/zendure-hub/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/zendure-solarflow-hub-bware',
    hint: 'solar hub',
    collection: 'Zendure Outlet',
  },
  {
    id: 'zendure-solarflow-ab2000-bware',
    brand: 'Zendure',
    name: 'Zendure SolarFlow AB2000 Zusatzbatterie 1920 Wh B-Ware',
    price: '531.00',
    image: 'https://picsum.photos/seed/zendure-battery/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/zendure-solarflow-ab2000-bware',
    hint: 'solar battery',
    collection: 'Zendure Outlet',
  },
  {
    id: 'dometic-cfx3-25-bware',
    brand: 'Dometic',
    name: 'Dometic CFX3 25 mobile Kompressorkühlbox B-Ware',
    price: '712.00',
    image: 'https://picsum.photos/seed/dometic-cfx3-25/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/dometic-cfx3-25-bware',
    hint: 'cooler box',
    collection: 'Dometic Outlet',
  },
  {
    id: 'dometic-cfx3-35-bware',
    brand: 'Dometic',
    name: 'Dometic CFX3 35 mobile Kompressorkühlbox B-Ware',
    price: '759.00',
    image: 'https://picsum.photos/seed/dometic-cfx3-35/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/dometic-cfx3-35-bware',
    hint: 'cooler box',
    collection: 'Dometic Outlet',
  },
  {
    id: 'trina-vertex-s-435w',
    brand: 'Trina Solar',
    name: 'Trina Vertex S+ 435 W N-Type Bifaziales Dual Glass PV-Modul',
    price: '65.00 - 2784.60',
    image: 'https://picsum.photos/seed/trina-vertex-435/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/trina-vertex-s-435w',
    hint: 'solar panel',
    collection: 'Trina Solar',
  },
  {
    id: 'trina-vertex-s-440w',
    brand: 'Trina Solar',
    name: 'Trina Vertex S+ 440 W',
    price: '65.00 - 2784.60',
    image: 'https://picsum.photos/seed/trina-vertex-440/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/trina-vertex-s-440w',
    hint: 'solar panel',
    collection: 'Trina Solar',
  },
  {
    id: 'ecoflow-delta-3-plus',
    brand: 'EcoFlow',
    name: 'EcoFlow Delta 3 Plus Powerstation',
    price: '660.00',
    image: 'https://picsum.photos/seed/ecoflow-delta-3/400/400',
    rating: 0,
    reviews: 0,
    questions: 0,
    href: '/products/ecoflow-delta-3-plus',
    hint: 'power station',
    collection: 'EcoFlow Outlet',
  },
];
